name: Auto apply triage label and add to project

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  label_and_assign_project:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: read
      project: write  # Required for actions/add-to-project

    steps:
      # 1. Add "triage" label if no milestone
      - name: Add "triage" label if no milestone
        if: ${{ github.event.issue.milestone == null }}
        run: gh issue edit ${{ github.event.issue.number }} --repo quantumjs/launch-track --add-label triage
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 2. Add issue to org-level project using actions/add-to-project
      - name: Add issue to project
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/quantumjs/projects/1
          content-id: ${{ github.event.issue.node_id }}
          token: ${{ secrets.GITHUB_TOKEN }}
